<div class="row">
    <div class="col col-lg-12 mx-auto">




        <div class="row">
<div class="col-12 col-lg-4 mx-auto">
							<div class="card radius-15">
								<div class="card-body">
									<div class="card-title">
										<h5 class="mb-0">Competencias Transversales</h5>
									</div>
									<hr/>
									<div class="chart-container2">
										<canvas id="chart1"></canvas>
									</div>
								</div>
							</div>
						</div>

            
            
            <div class="col-12 col-lg-4 mx-auto">
							<div class="card radius-15">
								<div class="card-body">
									<div class="card-title">
										<h5 class="mb-0">Competencias Disciplinarias</h5>
									</div>
									<hr/>
									<div class="chart-container2">
										<canvas id="chart2"></canvas>
									</div>
								</div>
							</div>
						</div>

            

            
            <div class="col-12 col-lg-4 mx-auto">
							<div class="card radius-15">
								<div class="card-body">
									<div class="card-title">
										<h5 class="mb-0">Comparativo</h5>
									</div>
									<hr/>
									<div class="chart-container2">
										<canvas id="chart3"></canvas>
									</div>
								</div>
							</div>
						</div>

        </div>








    </div>

</div>









<div class="card radius-15">
    <div class="card-body">
        <div class="card-title">
            <h5 class="mb-0">Mis Evaluadores</h5>

            <div class="progress">
                <div id="progress_evaluadores" class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" style="width: 25%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100">25%</div>
            </div>
        </div>
        <hr>
        <button class="btn btn-mondragon2" onclick="dAgregaRegistro()" id="agregaRegistro"><i class="fa-solid fa-circle-plus"></i> Nuevo Evaluador</button>
        <table id="list_evaluadores"></table>
        <div id="pager_evaluadores"></div>




        <input type="hidden" id="catalogo_id">

    </div>
</div>



<div class="card radius-15">
    <div class="card-body">
        <div class="card-title">
            <h5 class="mb-0">Mis Evaluaciones</h5>

            
        </div>
        <hr>
        <table id="list_evaluaciones"></table>
        <div id="pager_evaluaciones"></div>




       

    </div>
</div>








<div class="modal fade" id="dialog_catalogo" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header bg-mondragon2">
                <h5 class="modal-title text-white">Editar Registro</h5>
                <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form id="form_catalogo">


                    <div class="row"> 
                        <div class="col-lg-12 col-sm-12">
                            Nombre
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="fas fa-edit"></i></span>
                                <input type="text" class="form-control" id="nombre_evaluador" placeholder="Nombre del Evaluador" maxlength="50"/>
                            </div>
                        </div>
                    </div>





                    <div class="row"> 
                        <div class="col-lg-12 col-sm-12">
                            Rol
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="fas fa-edit"></i></span>
                                <span id="cont-rol_evaluador"></span>
                            </div>
                        </div>
                    </div>


                    <div class="row"> 
                        <div class="col-lg-12 col-sm-12">
                            Teléfono
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="fas fa-edit"></i></span>
                                <input type="text" class="form-control" id="telefono_evaluador" placeholder="Teléfono" maxlength="15"/>
                            </div>
                        </div>
                    </div>




                    <div class="row"> 
                        <div class="col-lg-12 col-sm-12">
                            Correo electrónico
                            <div class="input-group mb-3">
                                <span class="input-group-text"><i class="fas fa-edit"></i></span>
                                <input type="mail" class="form-control" id="correo_evaluador" placeholder="Correo Electrónico" maxlength="100"/>
                            </div>
                        </div>
                    </div>
                </form>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="guardaEvaluador()">Guardar</button>
            </div>
        </div>
    </div>
</div>


<div class="modal fade" id="dialog_edit_catalogo" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-mondragon2">
                <h5 class="modal-title text-white">Editar Registro</h5>
                <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">


                <div class="row"> 
                    <div class="col-lg-12 col-sm-12">
                        Persona
                        <div class="input-group mb-3">
                            <span class="input-group-text"><i class="fas fa-edit"></i></span>
                            <span id="cont-personas"></span>
                        </div>
                    </div>

                </div>


                <div class="row"> 
                    <div class="col-lg-12 col-sm-12">
                        Correo electrónico
                        <div class="input-group mb-3">
                            <span class="input-group-text"><i class="fas fa-at"></i></span>
                            <input type="mail" class="form-control" id="correo_persona" placeholder="Correo Electrónico" maxlength="25" disabled/>
                        </div>
                    </div>
                </div>


            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" onclick="editaCatalogo()">Guardar</button>
                
            </div>
        </div>
    </div>
</div>





















