<div class="modal fade " id="dialog_usuario" tabindex="-1" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content">
            <div class="modal-header bg-mondragon2">
                <h5 class="modal-title text-white">Detalle del Validador</h5>
                <button type="button" class="btn-close bg-white" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              
                
                <table id="list_carreras"></table>
                <div id="pager_carreras"></div>

            </div>
        </div>
    </div>
</div>