<div class="row">


    <div class="card radius-15">
        <div class="card-body">
<div class="row">
            <div class="col col-lg-2"></div>
            <div class="col col-lg-3">
            

                <div class="input-group">
                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-edit"></i></span></div>
                    <select class="form-control" id="subtipo" onchange="cambiaSubtipo(this.value)">
                        <option value="general">General</option>
                        <option value="carrera">Por Carrera</option>
                        <option value="semestre">Por Semestre</option>
                        <option value="especialidad">Por Especialidad</option>
                        
                        
                    </select>
                </div>
            </div>
            
            
            
            <div class="col col-lg-4">
                <div class="input-group">
                    <div class="input-group-prepend"><span class="input-group-text"><i class="fa fa-edit"></i></span></div>
                    <select id="filtro_sub" class="form-control" disabled onchange="cambiaFiltros();">
                    </select>
                    
                    
                </div>
            </div>
            
            
            
            
            
            </div>
        </div>
      


<div class="row">







    <div class="col col-lg-6">
        <div class="card radius-15">
            <div class="card-body">
                <div class="card-title">
                    <h5 class="mb-0">Transversales</h5>
                </div>
                <hr/>

                <div id="grafica-btrans"></div>




            </div>
        </div>
    </div>


    <div class="col col-lg-6">
        <div class="card radius-15">
            <div class="card-body">
                <div class="card-title">
                    <h5 class="mb-0">Disciplinarias</h5>
                </div>
                <hr/>

                <div id="grafica-bdis"></div>




            </div>
        </div>
    </div>






    <div class="col col-lg-12">
        <div class="card radius-15">
            <div class="card-body">
                <div class="card-title">
                    <h5 class="mb-0">Reporte General <button id="btn_exportar" class="btn btn-success" onclick="exportaRep()">Exportar</button></h5> 
                </div>
                <hr/>

                <table id="list_general"></table>
                <div id="pager_general"></div>




            </div>
        </div>
    </div>







</div>





<div class="row">
    <div class="col col-lg-4">
        <div class="card radius-15">
            <div class="card-body">
                <div class="card-title">
                    <h5 class="mb-0">Alumnos por Semestre</h5>
                </div>
                <hr/>

                <div id="grafica-poblacion"></div>





            </div>
        </div>
    </div>

    <div class="col col-lg-4">
        <div class="card radius-15">
            <div class="card-body">
                <div class="card-title">
                    <h5 class="mb-0">AutoEvaluaciones Realizadas</h5>
                </div>
                <hr/>

                <div id="grafica-aecompletas"></div>
            </div>
        </div>
    </div>




    <div class="col col-lg-4">
        <div class="card radius-15">
            <div class="card-body">
                <div class="card-title">
                    <h5 class="mb-0">Evaluaciones Jefe</h5>
                </div>
                <hr/>

                <div id="grafica-ejefes"></div>
            </div>
        </div>
    </div>


    <div class="col col-lg-4">
        <div class="card radius-15">
            <div class="card-body">
                <div class="card-title">
                    <h5 class="mb-0">Evaluaciones Colega</h5>
                </div>
                <hr/>

                <div id="grafica-ecolegas"></div>
            </div>
        </div>
    </div>






    <div class="col col-lg-6">
        <div class="card radius-15">
            <div class="card-body">
                <div class="card-title">
                    <h5 class="mb-0">Errores en envio de correo</h5>
                </div>
                <hr/>

                <table id="list_ecorreo"></table>
                <div id="pager_ecorreo"></div>




            </div>
        </div>
    </div>






</div>




    </div>




<section id="overlay" aria-hidden="true">
    <div class="spinner-border color-mondragon" style="width: 6rem; height: 6rem;" role="status"> <span class="visually-hidden">Loading...</span>								</div>
</section>