<div class="error-404 d-flex align-items-center justify-content-center">
    <div class="container">
        <div class="card radius-15 shadow-none">
            <div class="row g-0">
                <div class="col-lg-6">
                    <div class="card-body">
                        <h1 class="display-1"><span class="text-warning">5</span><span class="text-danger">0</span><span class="text-primary">0</span></h1>
                        <h2 class="font-weight-bold display-4">Error interno</h2>
                        <p>Se ha producido un error en el servidor
                            <br>Favor de reportarlo al administrador</p>
                        <div class="mt-5">
                            <a href="/" class="btn btn-lg btn-mondragon px-md-5 radius-30">Regresar</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6">
                    <img src="/img/errores/500.png" class="card-img" alt="">
                </div>
            </div>
            <!--end row-->
        </div>
    </div>
</div>