<section class="vh-100 gradient-custom">
        <div class="container py-5 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                    <div class="card card-login bg-white" style="border-radius: 1rem;">
                        <div class="card-login-body text-center">
                            <img id="logo-login"
                                src="/img/logo.png" alt="logo_mondragon">
                            <form id="form-login" action="" method="post" class="needs-validation" novalidate>
                                <div class="input-wrapper mt-4">
                                    <input type="email" id="usuario" class="form-control input-login" name="username"
                                        placeholder="Confirmar Correo electrónico" required>
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="input-icon"
                                        viewBox="0 0 16 16">
                                        <path
                                            d="M3 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H3zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z" />
                                    </svg>
                                    <div class="invalid-feedback text-start">
                                        Escriba un correo electrónico valido
                                    </div>
                                </div>
                                <div class="input-wrapper mt-5 mb-4">
                                    <input type="password" id="password" class="input-login form-control" name="password" placeholder="Nueva Contraseña"
                                        required>
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                                        class="input-icon key-input" viewBox="0 0 16 16">
                                        <path
                                            d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                                    </svg>
                                    <div class="invalid-feedback text-start">
                                        Debe introducir una contraseña
                                    </div>
                                </div>
                                
                                
                                <div class="input-wrapper mt-5 mb-4">
                                    <input type="password" id="password2" class="input-login form-control" name="password2" placeholder="Confirmar Contraseña"
                                        required>
                                    <svg xmlns="http://www.w3.org/2000/svg" fill="currentColor"
                                        class="input-icon key-input" viewBox="0 0 16 16">
                                        <path
                                            d="M3.5 11.5a3.5 3.5 0 1 1 3.163-5H14L15.5 8 14 9.5l-1-1-1 1-1-1-1 1-1-1-1 1H6.663a3.5 3.5 0 0 1-3.163 2zM2.5 9a1 1 0 1 0 0-2 1 1 0 0 0 0 2z" />
                                    </svg>
                                    <div class="invalid-feedback text-start">
                                        Debe introducir una contraseña
                                    </div>
                                </div>
                                
                                
                                
                                
                                <button class="btn btn-login mt-3" type="button" onclick="cambiaPassword()">Cambiar Contraseña</button>
                                
                                
                                
                                
                                <input type="hidden" id="token" name="token" value="<?php echo $token; ?>" />
                                
                                
                            </form>
                            

                        </div>
                    </div>
                    <div class="mt-3">
                        
                    </div>
                </div>
            </div>
        </div>
    </section>