<!DOCTYPE html>
<html lang="es">
    <head>
        <meta name="author" content="Juan Carlos Muñoz Luna" />
        <meta charset="utf-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="user-scalable=no,width=device-width" />

        <title>Login Mondragón</title>
        <link rel="shortcut icon" href="<?php echo $this->url->get('img/favicon.ico'); ?>" />
        <script type="text/javascript">
            var base_url = "<?php echo $this->url->getBaseUri(); ?>";
        </script> 

        <?php
        $this->assets->outputCss();
       
        ?>
    </head>



    <body>
        <?php echo $this->getContent(); ?>
    </body>
    
    
    <?php
       
        $this->assets->outputJs();
        ?>
    
    
</html>